# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-26 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='follows',
            new_name='test',
        ),
    ]
